Added almost empty file module.c Added bfd warning message in configure.ac. Makefiles now use CPPFLAGS and LDFLAGS.
git-svn-id: svn://svn.code.sf.net/p/lush/code@1035 0babfeb2-de4b-461b-a2bf-1ab085750f0d

diff --git a/lush1/trunk/configure b/lush1/trunk/configure
--- a/lush1/trunk/configure
+++ b/lush1/trunk/configure
@@ -846,6 +846,10 @@ Optional Features:
 Optional Packages:
   --with-PACKAGE[=ARG]    use PACKAGE [ARG=yes]
   --without-PACKAGE       do not use PACKAGE (same as --with-PACKAGE=no)
+  --with-extra-includes=DIR
+                          Define an additional directory for include files
+  --with-extra-libraries=DIR
+                          Define an additional directory for library files
   --with-x                use the X Window System
 
 Some influential environment variables:
@@ -1240,6 +1244,30 @@ host=$ac_cv_host
 host_cpu=`echo $ac_cv_host | sed 's/^\([^-]*\)-\([^-]*\)-\(.*\)$/\1/'`
 host_vendor=`echo $ac_cv_host | sed 's/^\([^-]*\)-\([^-]*\)-\(.*\)$/\2/'`
 host_os=`echo $ac_cv_host | sed 's/^\([^-]*\)-\([^-]*\)-\(.*\)$/\3/'`
+
+# Check whether --with-extra-includes or --without-extra-includes was given.
+if test "${with_extra_includes+set}" = set; then
+  withval="$with_extra_includes"
+   if test -d "$withval" ; then
+            CPPFLAGS="$CPPFLAGS -I$withval"
+          else
+            { { echo "$as_me:$LINENO: error: Cannot stat directory $withval" >&5
+echo "$as_me: error: Cannot stat directory $withval" >&2;}
+   { (exit 1); exit 1; }; }
+          fi
+fi;
+
+# Check whether --with-extra-libraries or --without-extra-libraries was given.
+if test "${with_extra_libraries+set}" = set; then
+  withval="$with_extra_libraries"
+   if test -d "$withval" ; then
+           LDFLAGS="$LDFLAGS -L$withval"
+          else
+            { { echo "$as_me:$LINENO: error: Cannot stat directory $withval" >&5
+echo "$as_me: error: Cannot stat directory $withval" >&2;}
+   { (exit 1); exit 1; }; }
+          fi
+fi;
 
 # ----------------------------------------
 # Programs
@@ -2550,7 +2578,7 @@ done
 fi
 
 # Provide some information about the compiler.
-echo "$as_me:2553:" \
+echo "$as_me:2581:" \
      "checking for Fortran 77 compiler version" >&5
 ac_compiler=`set X $ac_compile; echo $2`
 { (eval echo "$as_me:$LINENO: \"$ac_compiler --version </dev/null >&5\"") >&5
@@ -7384,9 +7412,6 @@ case "$host" in
         ;;
 esac
 
-echo "$as_me:$LINENO: checking " >&5
-echo $ECHO_N "checking ... $ECHO_C" >&6
-
 if test x$EXEEXT = xexe ; then
     SOEXT=dll
     DEFS="$DEFS -DWIN32"
@@ -7395,6 +7420,31 @@ if test x$EXEEXT = xexe ; then
 else
     UNIX_YES=''
     WIN32_YES='#'
+fi
+
+# ----------------------------------------
+# Diagnostics
+# ----------------------------------------
+
+if test x$BFD_YES != x ; then
+    { echo "$as_me:$LINENO: WARNING: Compiling without the BFD library.
+---------------------------------------------------
+This substantially reduces the capability of lush.
+* If you are using Linux, check that you have the
+  binutils-devel package, and check that its version
+  number matches the installed binutils.
+* Otherwise you should download and compile the
+  GNU binutils source on your system.
+---------------------------------------------------" >&5
+echo "$as_me: WARNING: Compiling without the BFD library.
+---------------------------------------------------
+This substantially reduces the capability of lush.
+* If you are using Linux, check that you have the
+  binutils-devel package, and check that its version
+  number matches the installed binutils.
+* Otherwise you should download and compile the
+  GNU binutils source on your system.
+---------------------------------------------------" >&2;}
 fi
 
 # ----------------------------------------
