Cygwin works!
git-svn-id: svn://svn.code.sf.net/p/lush/code@1709 0babfeb2-de4b-461b-a2bf-1ab085750f0d

diff --git a/lush1/trunk/configure b/lush1/trunk/configure
--- a/lush1/trunk/configure
+++ b/lush1/trunk/configure
@@ -886,7 +886,6 @@ Optional Packages:
   --with-extra-libraries=DIR
                           Define an additional directory for library files
   --without-bfd           Compile Lush without the BFD library.
-  --without-static-bfd    Do not try linking bfd statically.
   --with-x                use the X Window System
 
 Some influential environment variables:
@@ -2871,7 +2870,7 @@ fi
 
 
 # Provide some information about the compiler.
-echo "$as_me:2874:" \
+echo "$as_me:2873:" \
      "checking for Fortran 77 compiler version" >&5
 ac_compiler=`set X $ac_compile; echo $2`
 { (eval echo "$as_me:$LINENO: \"$ac_compiler --version </dev/null >&5\"") >&5
@@ -4356,8 +4355,260 @@ else
   has_bfd=no
 fi
 
-    if test x$has_bfd = xno ; then
-        { { echo "$as_me:$LINENO: error: Unable to locate BFD development files.
+fi
+
+
+# Check if it compiles
+if test x$has_bfd = xyes ; then
+    n_LIBS=$LIBS
+    has_intl=
+    echo "$as_me:$LINENO: checking for dcgettext in -lintl" >&5
+echo $ECHO_N "checking for dcgettext in -lintl... $ECHO_C" >&6
+if test "${ac_cv_lib_intl_dcgettext+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_check_lib_save_LIBS=$LIBS
+LIBS="-lintl  $LIBS"
+cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+/* Override any gcc2 internal prototype to avoid an error.  */
+#ifdef __cplusplus
+extern "C"
+#endif
+/* We use char because int might match the return type of a gcc2
+   builtin and then its argument prototype would still apply.  */
+char dcgettext ();
+int
+main ()
+{
+dcgettext ();
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+         { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_cv_lib_intl_dcgettext=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+ac_cv_lib_intl_dcgettext=no
+fi
+rm -f conftest.$ac_objext conftest$ac_exeext conftest.$ac_ext
+LIBS=$ac_check_lib_save_LIBS
+fi
+echo "$as_me:$LINENO: result: $ac_cv_lib_intl_dcgettext" >&5
+echo "${ECHO_T}$ac_cv_lib_intl_dcgettext" >&6
+if test $ac_cv_lib_intl_dcgettext = yes; then
+  has_intl=yes
+else
+  has_intl=no
+fi
+
+    i_LIBS=`echo $n_LIBS | sed -e 's/-liberty/& -lintl/'`
+    sn_LIBS=`echo $n_LIBS | sed -e 's/-lbfd\( -liberty\)*/-Wl,-Bstatic & -Wl,-Bdynamic/'`
+    si_LIBS=`echo $i_LIBS | sed -e 's/-lbfd\( -liberty\)*/-Wl,-Bstatic & -Wl,-Bdynamic/'`
+    LIBS=$sn_LIBS
+    echo "$as_me:$LINENO: checking whether bfd works with -Bstatic" >&5
+echo $ECHO_N "checking whether bfd works with -Bstatic... $ECHO_C" >&6
+    cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+#include "bfd.h"
+int
+main ()
+{
+bfd_openr("junk1","default");
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+         { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  okay_bfd=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+okay_bfd=no
+fi
+rm -f conftest.$ac_objext conftest$ac_exeext conftest.$ac_ext;
+    echo "$as_me:$LINENO: result: $okay_bfd" >&5
+echo "${ECHO_T}$okay_bfd" >&6
+    if test x$okay_bfd = xno ; then
+	if test x$has_intl = xyes ; then
+	    LIBS=$si_LIBS
+	    echo "$as_me:$LINENO: checking whether bfd works with -Bstatic and -lintl" >&5
+echo $ECHO_N "checking whether bfd works with -Bstatic and -lintl... $ECHO_C" >&6
+	    cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+#include "bfd.h"
+int
+main ()
+{
+bfd_openr("junk1","default");
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+         { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  okay_bfd=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+okay_bfd=no
+fi
+rm -f conftest.$ac_objext conftest$ac_exeext conftest.$ac_ext;
+	    echo "$as_me:$LINENO: result: $okay_bfd" >&5
+echo "${ECHO_T}$okay_bfd" >&6
+	fi
+	if test x$okay_bfd = xno ; then
+	    LIBS=$n_LIBS
+	    echo "$as_me:$LINENO: checking whether bfd works alone" >&5
+echo $ECHO_N "checking whether bfd works alone... $ECHO_C" >&6
+	    cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+#include "bfd.h"
+int
+main ()
+{
+bfd_openr("junk1","default");
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+         { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  okay_bfd=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+okay_bfd=no
+fi
+rm -f conftest.$ac_objext conftest$ac_exeext conftest.$ac_ext;
+	    echo "$as_me:$LINENO: result: $okay_bfd" >&5
+echo "${ECHO_T}$okay_bfd" >&6
+	    if test x$okay_bfd = xno ; then
+		if test x$has_intl = xyes ; then
+		    LIBS=$i_LIBS
+		    echo "$as_me:$LINENO: checking whether bfd works with -lintl" >&5
+echo $ECHO_N "checking whether bfd works with -lintl... $ECHO_C" >&6
+		    cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+#include "bfd.h"
+int
+main ()
+{
+bfd_openr("junk1","default");
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+         { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  okay_bfd=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+okay_bfd=no
+fi
+rm -f conftest.$ac_objext conftest$ac_exeext conftest.$ac_ext;
+		    echo "$as_me:$LINENO: result: $okay_bfd" >&5
+echo "${ECHO_T}$okay_bfd" >&6
+		fi
+		if test x$okay_bfd = xno ; then
+		    LIBS=$n_LIBS
+		fi
+	    fi
+	fi
+    fi
+    if test x$okay_bfd = xno ; then
+	has_bfd=no
+    fi
+fi
+
+if test x$has_bfd = xno ; then
+    { { echo "$as_me:$LINENO: error: Unable to locate BFD development files.
 -------------------------------------------------------------
 We were unable to locate required GNU binutils files.
 - Some Linux distributions do not install these by default.
@@ -4378,70 +4629,7 @@ option \"--without-bfd\".  The dynamic loader/linker/compiler
 will not work and Lush will be seriously crippled.
 -----------------------------------------------------------------" >&2;}
    { (exit 1); exit 1; }; }
-    fi
 fi
-
-
-# static bfd
-if test x$has_bfd = xyes ; then
-
-# Check whether --with-static-bfd or --without-static-bfd was given.
-if test "${with_static_bfd+set}" = set; then
-  withval="$with_static_bfd"
-  static_bfd=$withval
-else
-  static_bfd=yes
-fi;
-
-    if test x$static_bfd = xyes ; then
-        echo "$as_me:$LINENO: checking whether bfd works with option -Bstatic." >&5
-echo $ECHO_N "checking whether bfd works with option -Bstatic.... $ECHO_C" >&6
-        saved_LIBS=$LIBS
-        LIBS=`echo $LIBS | sed -e 's/-lbfd\( -liberty\)*/-Wl,-Bstatic & -Wl,-Bdynamic/'`
-        cat >conftest.$ac_ext <<_ACEOF
-#line $LINENO "configure"
-/* confdefs.h.  */
-_ACEOF
-cat confdefs.h >>conftest.$ac_ext
-cat >>conftest.$ac_ext <<_ACEOF
-/* end confdefs.h.  */
-#include "bfd.h"
-int
-main ()
-{
- bfd_init();
-  ;
-  return 0;
-}
-_ACEOF
-rm -f conftest.$ac_objext conftest$ac_exeext
-if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
-  (eval $ac_link) 2>&5
-  ac_status=$?
-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); } &&
-         { ac_try='test -s conftest$ac_exeext'
-  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
-  (eval $ac_try) 2>&5
-  ac_status=$?
-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); }; }; then
-  :
-else
-  echo "$as_me: failed program was:" >&5
-sed 's/^/| /' conftest.$ac_ext >&5
-
-static_bfd=no
-fi
-rm -f conftest.$ac_objext conftest$ac_exeext conftest.$ac_ext;
-        echo "$as_me:$LINENO: result: $static_bfd" >&5
-echo "${ECHO_T}$static_bfd" >&6
-        if test $static_bfd = xno ; then
-            LIBS=$saved_LIBS
-        fi
-    fi
-fi
-
 
 # x11
 echo "$as_me:$LINENO: checking for X" >&5
@@ -5641,12 +5829,15 @@ fi
 fi
 
 X_LIBS=
+X_CFLAGS=
 test -n "$x_libraries" && X_LIBS="-L$x_libraries"
+test -n "$x_includes" && X_CFLAGS="-I$x_includes"
 X_YES='#'
 if test "${no_x-no}" != yes ; then
   X_LIBS="$X_LIBS $X_PRE_LIBS -lX11 $X_EXTRA_LIBS"
   X_YES=''
 fi
+
 
 
 
@@ -9579,15 +9770,8 @@ esac
 
 
 
-if test x$EXEEXT = xexe ; then
-    SOEXT=dll
-    DEFS="$DEFS -DWIN32"
-    UNIX_YES='#'
-    WIN32_YES=''
-else
-    UNIX_YES=''
-    WIN32_YES='#'
-fi
+UNIX_YES=''
+WIN32_YES='#'
 
 
 
