Try linking bfd statically.
git-svn-id: svn://svn.code.sf.net/p/lush/code@1694 0babfeb2-de4b-461b-a2bf-1ab085750f0d

diff --git a/lush1/trunk/configure b/lush1/trunk/configure
--- a/lush1/trunk/configure
+++ b/lush1/trunk/configure
@@ -869,6 +869,7 @@ Optional Packages:
   --with-extra-libraries=DIR
                           Define an additional directory for library files
   --without-bfd           Compile Lush without the BFD library.
+  --without-static-bfd    Do not try linking bfd statically.
   --with-x                use the X Window System
 
 Some influential environment variables:
@@ -2689,7 +2690,7 @@ fi
 
 
 # Provide some information about the compiler.
-echo "$as_me:2692:" \
+echo "$as_me:2693:" \
      "checking for Fortran 77 compiler version" >&5
 ac_compiler=`set X $ac_compile; echo $2`
 { (eval echo "$as_me:$LINENO: \"$ac_compiler --version </dev/null >&5\"") >&5
@@ -4100,6 +4101,67 @@ will not work and Lush will be seriously crippled.
     fi
 fi
 
+
+# static bfd
+if test x$has_bfd = xyes ; then
+
+# Check whether --with-static-bfd or --without-static-bfd was given.
+if test "${with_static_bfd+set}" = set; then
+  withval="$with_static_bfd"
+  static_bfd=$withval
+else
+  static_bfd=yes
+fi;
+
+    if test x$static_bfd = xyes ; then
+        echo "$as_me:$LINENO: checking whether bfd works with option -Bstatic." >&5
+echo $ECHO_N "checking whether bfd works with option -Bstatic.... $ECHO_C" >&6
+        saved_LIBS=$LIBS
+        LIBS=`echo $LIBS | sed -e 's/-lbfd\( -liberty\)*/-Wl,-Bstatic & -Wl,-Bdynamic/'`
+        cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+#include "confdefs.h"
+#include "bfd.h"
+#ifdef F77_DUMMY_MAIN
+#  ifdef __cplusplus
+     extern "C"
+#  endif
+   int F77_DUMMY_MAIN() { return 1; }
+#endif
+int
+main ()
+{
+ bfd_init();
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+         { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  :
+else
+  echo "$as_me: failed program was:" >&5
+cat conftest.$ac_ext >&5
+static_bfd=no
+fi
+rm -f conftest.$ac_objext conftest$ac_exeext conftest.$ac_ext;
+        echo "$as_me:$LINENO: result: $static_bfd" >&5
+echo "${ECHO_T}$static_bfd" >&6
+        if test $static_bfd = xno ; then
+            LIBS=$saved_LIBS
+        fi
+    fi
+fi
 
 
 # x11
